[tools]
"github:crate-ci/committed" = "latest"
dprint = "latest"
fnox = "1.28.0"
gitleaks = "latest"
lefthook = "latest"
pitchfork = "latest"

[hooks]
postinstall = "lefthook install"

[tasks.fmt]
description = "Formats all supported files"
run = "cargo fmt && dprint fmt"

[tasks.fmt-check]
description = "Checks formatting and fails on differences"
run = "cargo fmt --check && dprint check"
